#!/usr/bin/env bash
# Emit OpenTofu import blocks for every DNS record in a zone.
#
# Cloudflare DNS records import as "<zone_id>/<record_id>", so the record ids
# have to come from the API — you cannot write these by hand from the dashboard
# without a lot of clicking.
#
# Usage:
#   export CLOUDFLARE_API_TOKEN=$(kp-get "Cloudflare General Token")
#   ./scripts/gen-dns-imports.sh lab.example > live/imports-dns-lab-example.tf
#
# Then write the matching resource blocks (or let
# `tofu plan -generate-config-out=generated.tf` draft them) and review before
# applying. Nothing here writes to Cloudflare; it is read-only.

set -euo pipefail

ZONE_NAME="${1:?usage: $0 <zone-name>}"
API="https://api.cloudflare.com/client/v4"

: "${CLOUDFLARE_API_TOKEN:?CLOUDFLARE_API_TOKEN must be set}"

auth=(-H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}")

zone_id=$(curl -sS "${auth[@]}" "${API}/zones?name=${ZONE_NAME}" |
  jq -r '.result[0].id // empty')

if [ -z "$zone_id" ]; then
  echo "zone not found (or token lacks Zone:Read on it): ${ZONE_NAME}" >&2
  exit 1
fi

# Sanitise a record into a stable, unique-ish Terraform resource name.
# Name and type together are not always unique (round-robin A records), so the
# record id suffix keeps collisions out.
printf '# Auto-generated by scripts/gen-dns-imports.sh for zone %s\n' "$ZONE_NAME"
printf '# zone_id = %s\n\n' "$zone_id"

page=1
while :; do
  body=$(curl -sS "${auth[@]}" "${API}/zones/${zone_id}/dns_records?per_page=100&page=${page}")

  count=$(printf '%s' "$body" | jq '.result | length')
  [ "$count" -eq 0 ] && break

  printf '%s' "$body" | jq -r --arg zid "$zone_id" '
    .result[]
    | . as $r
    | ($r.name
        | gsub("\\*"; "wildcard")
        | gsub("[^a-zA-Z0-9]"; "_")) as $slug
    | "import {\n  to = cloudflare_dns_record.\($slug)_\($r.type | ascii_downcase)_\($r.id[0:6])\n  id = \"\($zid)/\($r.id)\"\n}\n"
  '

  total_pages=$(printf '%s' "$body" | jq '.result_info.total_pages // 1')
  [ "$page" -ge "$total_pages" ] && break
  page=$((page + 1))
done
